version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'V1RE'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'V1RE'

  - package-ecosystem: 'npm'
    directory: '/packages/tsconfig'
    schedule:
      interval: 'daily'
    reviewers:
      - 'V1RE'

  - package-ecosystem: 'npm'
    directory: '/packages/eslint'
    schedule:
      interval: 'daily'
    reviewers:
      - 'V1RE'

  - package-ecosystem: 'npm'
    directory: '/packages/prettier'
    schedule:
      interval: 'daily'
    reviewers:
      - 'V1RE'
