#:schema https://mise.jdx.dev/schema/mise.json

[env]
FORCE_COLOR = "1"
NODE_OPTIONS = "--no-deprecation"

[settings]
pin = true
ignored_config_paths = ["**/fixtures/**"]
idiomatic_version_file_enable_tools = ["node", "pnpm"]

[hooks]
enter = "mise i -q"
