packages:
  - packages/*

catalog:
  '@arethetypeswrong/core': 0.18.2
  '@changesets/cli': 2.29.8
  '@effect/ai': 0.33.2
  '@effect/cli': 0.73.2
  '@effect/experimental': 0.58.0
  '@effect/language-service': 0.76.0
  '@effect/platform': 0.94.5
  '@effect/platform-node': 0.104.1
  '@effect/rpc': 0.73.2
  '@effect/vitest': 0.27.0
  '@eslint-community/eslint-plugin-eslint-comments': 4.6.0
  '@eslint-react/eslint-plugin': 2.13.0
  '@eslint/compat': 2.0.2
  '@eslint/config-inspector': 1.4.2
  '@eslint/css': 0.14.1
  '@eslint/js': 10.0.1
  '@eslint/markdown': 7.5.1
  '@graphql-eslint/eslint-plugin': 4.4.0
  '@ianvs/prettier-plugin-sort-imports': 4.7.1
  '@manypkg/cli': 0.25.1
  '@next/eslint-plugin-next': 16.1.6
  '@opencode-ai/plugin': 1.2.12
  '@prettier/plugin-oxc': 0.1.3
  '@prettier/plugin-xml': 3.4.2
  '@stylistic/eslint-plugin': 5.9.0
  '@tanstack/eslint-plugin-query': 5.91.4
  '@tanstack/eslint-plugin-router': 1.161.4
  '@types/bun': 1.3.9
  '@types/node': 24.10.13
  '@types/react': 19.2.14
  '@typescript-eslint/parser': 8.56.1
  '@typescript-eslint/scope-manager': 8.56.1
  '@typescript-eslint/utils': 8.56.1
  '@typescript/native-preview': 7.0.0-dev.20260225.1
  bunup: 0.16.29
  dedent: 1.7.1
  effect: 3.19.19
  empathic: 2.0.0
  eslint: 10.0.2
  eslint-config-flat-gitignore: 2.2.1
  eslint-config-prettier: 10.1.8
  eslint-flat-config-utils: 3.0.1
  eslint-merge-processors: 2.0.0
  eslint-plugin-antfu: 3.2.2
  eslint-plugin-de-morgan: 2.0.0
  eslint-plugin-depend: 1.4.0
  eslint-plugin-drizzle: 0.2.3
  eslint-plugin-github-action: 0.1.0
  eslint-plugin-jsdoc: 62.7.1
  eslint-plugin-jsonc: 3.1.0
  eslint-plugin-n: 17.24.0
  eslint-plugin-pnpm: 1.6.0
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-regexp: 3.0.0
  eslint-plugin-sonarjs: 4.0.0
  eslint-plugin-storybook: 10.2.12
  eslint-plugin-tailwindcss: 3.18.2
  eslint-plugin-toml: 1.3.0
  eslint-plugin-turbo: 2.8.10
  eslint-plugin-unicorn: 63.0.0
  eslint-plugin-yml: 3.3.0
  eslint-plugin-zod: 3.1.0
  eslint-typegen: 2.3.1
  eslint-vitest-rule-tester: 3.1.0
  globals: 17.3.0
  graphql-config: 5.1.5
  jsonc-eslint-parser: 3.1.0
  knip: 5.85.0
  local-pkg: 1.1.2
  nolyfill: 1.0.44
  nypm: 0.6.5
  pkg-pr-new: 0.0.63
  pkg-types: 2.3.0
  prettier: 3.8.1
  prettier-plugin-jsdoc: 1.8.0
  prettier-plugin-tailwindcss: 0.7.2
  publint: 0.3.17
  react: 19.2.4
  renovate: 43.36.0
  tailwind-csstree: 0.1.4
  tinyexec: 1.0.2
  tinyglobby: 0.2.15
  ts-api-utils: 2.4.0
  tsdown: 0.20.3
  tsx: 4.21.0
  turbo: 2.8.10
  typescript: 5.9.3
  typescript-eslint: 8.56.1
  unplugin-replace: 0.6.3
  vitest: 4.0.18
  yaml-eslint-parser: 2.0.0
  zod: 4.3.6

catalogMode: strict

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@bunup/dts'
  - msgpackr-extract

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - oxc-resolver
  - protobufjs
  - re2

optimisticRepeatInstall: true

overrides:
  array-includes: npm:@nolyfill/array-includes@1.0.44
  array.prototype.findlast: npm:@nolyfill/array.prototype.findlast@1.0.44
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@1.0.44
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@1.0.44
  array.prototype.tosorted: npm:@nolyfill/array.prototype.tosorted@1.0.44
  baseline-browser-mapping: 2.10.0
  es-iterator-helpers: npm:@nolyfill/es-iterator-helpers@1.0.21
  globalthis: npm:@nolyfill/globalthis@1.0.44
  hasown: npm:@nolyfill/hasown@1.0.44
  is-arguments: npm:@nolyfill/is-arguments@1.0.44
  is-core-module: npm:@nolyfill/is-core-module@1.0.39
  is-generator-function: npm:@nolyfill/is-generator-function@1.0.44
  is-typed-array: npm:@nolyfill/is-typed-array@1.0.44
  isarray: npm:@nolyfill/isarray@1.0.44
  object.assign: npm:@nolyfill/object.assign@1.0.44
  object.entries: npm:@nolyfill/object.entries@1.0.44
  object.fromentries: npm:@nolyfill/object.fromentries@1.0.44
  object.values: npm:@nolyfill/object.values@1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@1.0.44
  side-channel: npm:@nolyfill/side-channel@1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@1.0.44
  string.prototype.repeat: npm:@nolyfill/string.prototype.repeat@1.0.44
  which-typed-array: npm:@nolyfill/which-typed-array@1.0.44

patchedDependencies:
  '@eslint/plugin-kit@0.6.0': patches/@eslint__plugin-kit@0.6.0.patch

preferWorkspacePackages: true

savePrefix: ''
