verifyDepsBeforeRun: install
savePrefix: ''

packages:
  - packages/*
catalog:
  '@changesets/cli': 2.28.1
  '@eslint-community/eslint-plugin-eslint-comments': 4.4.1
  '@eslint-react/eslint-plugin': 1.30.0
  '@eslint/compat': 1.2.7
  '@eslint/config-inspector': 1.0.1
  '@eslint/core': 0.12.0
  '@eslint/css': 0.4.0
  '@eslint/js': 9.21.0
  '@eslint/plugin-kit': 0.2.7
  '@graphql-eslint/eslint-plugin': 4.3.0
  '@ianvs/prettier-plugin-sort-imports': 4.4.1
  '@manypkg/cli': 0.23.0
  '@next/eslint-plugin-next': 15.2.1
  '@prettier/plugin-xml': 3.4.1
  '@tanstack/eslint-plugin-query': 5.66.1
  '@types/node': 22.13.9
  '@typescript-eslint/parser': 8.26.0
  '@typescript-eslint/utils': 8.26.0
  css-tree: 3.1.0
  eslint: 9.21.0
  eslint-config-flat-gitignore: 2.1.0
  eslint-config-prettier: 10.0.2
  eslint-flat-config-utils: 2.0.1
  eslint-plugin-antfu: 3.1.0
  eslint-plugin-de-morgan: 1.2.0
  eslint-plugin-drizzle: 0.2.3
  eslint-plugin-jsdoc: 50.6.3
  eslint-plugin-jsonc: 2.19.1
  eslint-plugin-n: 17.16.1
  eslint-plugin-react: 7.37.4
  eslint-plugin-react-compiler: 19.0.0-beta-e552027-20250112
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-regexp: 2.7.0
  eslint-plugin-sonarjs: 3.0.2
  eslint-plugin-storybook: 0.11.3
  eslint-plugin-tailwindcss: 3.18.0
  eslint-plugin-turbo: 2.4.4
  eslint-plugin-unicorn: 57.0.0
  eslint-typegen: 2.0.0
  eslint-vitest-rule-tester: 1.1.0
  find-up: 7.0.0
  globals: 16.0.0
  graphql-config: 5.1.3
  jsonc-eslint-parser: 2.4.0
  local-pkg: 1.1.1
  magic-regexp: 0.8.0
  pkg-pr-new: 0.0.40
  prettier: 3.5.3
  prettier-plugin-embed: 0.5.0
  prettier-plugin-jsdoc: 1.3.2
  prettier-plugin-sh: 0.15.0
  prettier-plugin-sql: 0.18.1
  prettier-plugin-tailwindcss: 0.6.11
  prettier-plugin-toml: 2.0.2
  renovate: 39.188.4
  ts-pattern: 5.6.2
  tsup: 8.4.0
  turbo: 2.4.4
  typescript: 5.8.2
  typescript-eslint: 8.26.0
  vitest: 3.0.8
