packages:
  - packages/*
overrides:
  array-includes: npm:@nolyfill/array-includes@1.0.44
  array.prototype.findlast: npm:@nolyfill/array.prototype.findlast@1.0.44
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@1.0.44
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@1.0.44
  array.prototype.tosorted: npm:@nolyfill/array.prototype.tosorted@1.0.44
  es-iterator-helpers: npm:@nolyfill/es-iterator-helpers@1.0.21
  globalthis: npm:@nolyfill/globalthis@1.0.44
  hasown: npm:@nolyfill/hasown@1.0.44
  is-arguments: npm:@nolyfill/is-arguments@1.0.44
  is-core-module: npm:@nolyfill/is-core-module@1.0.39
  is-generator-function: npm:@nolyfill/is-generator-function@1.0.44
  is-typed-array: npm:@nolyfill/is-typed-array@1.0.44
  isarray: npm:@nolyfill/isarray@1.0.44
  object.assign: npm:@nolyfill/object.assign@1.0.44
  object.entries: npm:@nolyfill/object.entries@1.0.44
  object.fromentries: npm:@nolyfill/object.fromentries@1.0.44
  object.values: npm:@nolyfill/object.values@1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@1.0.44
  side-channel: npm:@nolyfill/side-channel@1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@1.0.44
  string.prototype.repeat: npm:@nolyfill/string.prototype.repeat@1.0.44
  which-typed-array: npm:@nolyfill/which-typed-array@1.0.44
catalog:
  '@changesets/cli': 2.28.1
  '@eslint-community/eslint-plugin-eslint-comments': 4.4.1
  '@eslint-react/eslint-plugin': 1.38.3
  '@eslint/compat': 1.2.7
  '@eslint/config-inspector': 1.0.2
  '@eslint/css': 0.6.0
  '@eslint/js': 9.23.0
  '@eslint/markdown': 6.3.0
  '@graphql-eslint/eslint-plugin': 4.4.0
  '@ianvs/prettier-plugin-sort-imports': 4.4.1
  '@manypkg/cli': 0.23.0
  '@next/eslint-plugin-next': 15.2.4
  '@prettier/plugin-xml': 3.4.1
  '@stylistic/eslint-plugin': 4.2.0
  '@tanstack/eslint-plugin-query': 5.68.0
  '@types/node': 22.13.14
  '@types/react': 19.0.12
  '@typescript-eslint/parser': 8.28.0
  '@typescript-eslint/utils': 8.28.0
  dedent: 1.5.3
  eslint: 9.23.0
  eslint-config-flat-gitignore: 2.1.0
  eslint-config-prettier: 10.1.1
  eslint-flat-config-utils: 2.0.1
  eslint-merge-processors: 2.0.0
  eslint-plugin-antfu: 3.1.1
  eslint-plugin-de-morgan: 1.2.1
  eslint-plugin-drizzle: 0.2.3
  eslint-plugin-jsdoc: 50.6.9
  eslint-plugin-jsonc: 2.20.0
  eslint-plugin-n: 17.17.0
  eslint-plugin-pnpm: 0.3.1
  eslint-plugin-react-compiler: 19.0.0-beta-e552027-20250112
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-regexp: 2.7.0
  eslint-plugin-sonarjs: 3.0.2
  eslint-plugin-storybook: 0.12.0
  eslint-plugin-tailwindcss: 3.18.0
  eslint-plugin-turbo: 2.4.4
  eslint-plugin-unicorn: 58.0.0
  eslint-plugin-yml: 1.17.0
  eslint-typegen: 2.1.0
  eslint-vitest-rule-tester: 2.2.0
  execa: 9.5.2
  find-up: 7.0.0
  globals: 16.0.0
  graphql-config: 5.1.3
  jsonc-eslint-parser: 2.4.0
  knip: 5.46.2
  local-pkg: 1.1.1
  magic-regexp: 0.8.0
  nolyfill: 1.0.44
  pkg-pr-new: 0.0.41
  prettier: 3.5.3
  prettier-plugin-embed: 0.5.0
  prettier-plugin-jsdoc: 1.3.2
  prettier-plugin-sh: 0.15.0
  prettier-plugin-sql: 0.18.1
  prettier-plugin-tailwindcss: 0.6.11
  prettier-plugin-toml: 2.0.2
  react: 19.0.0
  renovate: 39.219.3
  tinyglobby: 0.2.12
  ts-pattern: 5.6.2
  tsup: 8.4.0
  turbo: 2.4.4
  typescript: 5.8.2
  typescript-eslint: 8.28.0
  vitest: 3.0.9
  yaml-eslint-parser: 1.3.0
onlyBuiltDependencies:
  - esbuild
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - protobufjs
  - re2
verifyDepsBeforeRun: install
savePrefix: ''
