packages:
  - packages/*

catalog:
  '@changesets/cli': 2.29.7
  '@effect/cli': 0.71.0
  '@effect/language-service': 0.41.1
  '@effect/platform': 0.92.1
  '@effect/platform-node': 0.98.2
  '@eslint-community/eslint-plugin-eslint-comments': 4.5.0
  '@eslint-react/eslint-plugin': 2.0.4
  '@eslint/compat': 1.4.0
  '@eslint/config-inspector': 1.3.0
  '@eslint/css': 0.11.1
  '@eslint/js': 9.36.0
  '@eslint/markdown': 7.3.0
  '@graphql-eslint/eslint-plugin': 4.4.0
  '@ianvs/prettier-plugin-sort-imports': 4.7.0
  '@manypkg/cli': 0.25.1
  '@next/eslint-plugin-next': 15.5.4
  '@prettier/plugin-oxc': 0.0.4
  '@prettier/plugin-xml': 3.4.2
  '@stylistic/eslint-plugin': 5.4.0
  '@tanstack/eslint-plugin-query': 5.91.0
  '@types/node': 22.18.8
  '@types/react': 19.1.17
  '@typescript-eslint/parser': 8.45.0
  '@typescript-eslint/utils': 8.45.0
  dedent: 1.7.0
  effect: 3.18.1
  eslint: 9.36.0
  eslint-config-flat-gitignore: 2.1.0
  eslint-config-prettier: 10.1.8
  eslint-flat-config-utils: 2.1.4
  eslint-merge-processors: 2.0.0
  eslint-plugin-antfu: 3.1.1
  eslint-plugin-de-morgan: 2.0.0
  eslint-plugin-drizzle: 0.2.3
  eslint-plugin-github-action: 0.0.16
  eslint-plugin-jsdoc: 60.7.0
  eslint-plugin-jsonc: 2.20.1
  eslint-plugin-n: 17.23.1
  eslint-plugin-pnpm: 1.2.0
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-hooks: 5.2.0
  eslint-plugin-regexp: 2.10.0
  eslint-plugin-sonarjs: 3.0.5
  eslint-plugin-storybook: 9.1.10
  eslint-plugin-tailwindcss: 3.18.2
  eslint-plugin-turbo: 2.5.8
  eslint-plugin-unicorn: 61.0.2
  eslint-plugin-yml: 1.18.0
  eslint-typegen: 2.3.0
  eslint-vitest-rule-tester: 2.2.2
  execa: 9.6.0
  find-up: 8.0.0
  globals: 16.4.0
  graphql-config: 5.1.5
  jsonc-eslint-parser: 2.4.1
  knip: 5.64.1
  local-pkg: 1.1.2
  magic-regexp: 0.10.0
  nolyfill: 1.0.44
  nypm: 0.6.2
  pkg-pr-new: 0.0.60
  pkg-types: 2.3.0
  prettier: 3.6.2
  prettier-plugin-jsdoc: 1.3.3
  prettier-plugin-tailwindcss: 0.6.14
  react: 19.1.1
  renovate: 41.132.5
  tailwind-csstree: 0.1.4
  tinyglobby: 0.2.15
  ts-pattern: 5.8.0
  tsdown: 0.15.6
  tsx: 4.20.6
  turbo: 2.5.8
  typescript: 5.9.3
  typescript-eslint: 8.45.0
  unplugin-replace: 0.6.1
  vitest: 3.2.4
  yaml-eslint-parser: 1.3.0

catalogMode: strict

ignoredBuiltDependencies:
  - msgpackr-extract

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - core-js-pure
  - dtrace-provider
  - esbuild
  - oxc-resolver
  - protobufjs
  - re2

optimisticRepeatInstall: true

overrides:
  array-includes: npm:@nolyfill/array-includes@1.0.44
  array.prototype.findlast: npm:@nolyfill/array.prototype.findlast@1.0.44
  array.prototype.flat: npm:@nolyfill/array.prototype.flat@1.0.44
  array.prototype.flatmap: npm:@nolyfill/array.prototype.flatmap@1.0.44
  array.prototype.tosorted: npm:@nolyfill/array.prototype.tosorted@1.0.44
  es-iterator-helpers: npm:@nolyfill/es-iterator-helpers@1.0.21
  globalthis: npm:@nolyfill/globalthis@1.0.44
  hasown: npm:@nolyfill/hasown@1.0.44
  is-arguments: npm:@nolyfill/is-arguments@1.0.44
  is-core-module: npm:@nolyfill/is-core-module@1.0.39
  is-generator-function: npm:@nolyfill/is-generator-function@1.0.44
  is-typed-array: npm:@nolyfill/is-typed-array@1.0.44
  isarray: npm:@nolyfill/isarray@1.0.44
  object.assign: npm:@nolyfill/object.assign@1.0.44
  object.entries: npm:@nolyfill/object.entries@1.0.44
  object.fromentries: npm:@nolyfill/object.fromentries@1.0.44
  object.values: npm:@nolyfill/object.values@1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@1.0.44
  side-channel: npm:@nolyfill/side-channel@1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@1.0.44
  string.prototype.repeat: npm:@nolyfill/string.prototype.repeat@1.0.44
  which-typed-array: npm:@nolyfill/which-typed-array@1.0.44

savePrefix: ''
