export const tailwindFunctions = ['tv', 'cn', 'cnBase', 'classnames', 'clsx', 'cx'];

export const ignorePatterns = [
  '**/node_modules',
  '**/dist',
  '**/package-lock.json',
  '**/yarn.lock',
  '**/pnpm-lock.yaml',
  '**/bun.lockb',
  '**/bun.lock',
  '**/output',
  '**/coverage',
  '**/temp',
  '**/.temp',
  '**/tmp',
  '**/.tmp',
  '**/.history',
  '**/.nuxt',
  '**/.next',
  '**/.vercel',
  '**/.changeset',
  '**/.idea',
  '**/.cache',
  '**/.output',
  '**/.yarn',
  '**/CHANGELOG*.md',
  '**/*.min.*',
  '**/LICENSE*',
  '**/__snapshots__',
  '**/__snapshots__/**',
  '**/auto-import?(s).d.ts',
  '**/components.d.ts',
  '**/.agents/skills/**',
  '**/fixtures/**',
];
