export const PluginNameMap = {
  '@next/next': 'next',
  '@eslint-react/naming-convention': 'react-naming-convention',
  '@eslint-react/hooks-extra': 'react-hooks-extra',
  '@eslint-react/dom': 'react-dom',
  '@eslint-react': 'react-extra',
  'react-hooks': 'react-hooks',
  'react-compiler': 'react-compiler',
  react: 'react',
  '@typescript-eslint': 'ts',
  node: 'node',
  'eslint-comments': 'eslint-comments',
  storybook: 'storybook',
  turbo: 'turbo',
  jsdoc: 'jsdoc',
  unicorn: 'unicorn',
  tailwindcss: 'tailwindcss',
  '@tanstack/query': 'tanstack',
  '@2digits': '@2digits',
} as const;
