export const PluginNameMap = {
  '@next/next': 'next',
  '@eslint-react': 'react-extra',
  'react-hooks': 'react-hooks',
  'react-compiler': 'react-compiler',
  '@stylistic/eslint-plugin': 'stylistic',
  '@typescript-eslint': 'ts',
  vitest: 'vitest',
  node: 'node',
  '@eslint-community/eslint-comments': 'comments',
  storybook: 'storybook',
  turbo: 'turbo',
  jsdoc: 'jsdoc',
  unicorn: 'unicorn',
  tailwindcss: 'tailwindcss',
  '@tanstack/query': 'tanstack-query',
  '@tanstack/router': 'tanstack-router',
  '@2digits': '@2digits',
  '@graphql-eslint': 'gql',
  sonarjs: 'sonar',
  drizzle: 'drizzle',
  'de-morgan': 'boolean',
  antfu: 'antfu',
  css: 'css',
  depend: 'depend',
  'github-action': 'github-action',
  jsonc: 'jsonc',
  markdown: 'markdown',
  pnpm: 'pnpm',
  regexp: 'regexp',
  yml: 'yml',
  zod: 'zod',
  toml: 'toml',
} as const;

export const storybookPackages = [
  'storybook',
  '@storybook/nextjs',
  '@storybook/nextjs-vite',
  '@storybook/react-vite',
  '@storybook/react-webpack5',
  '@storybook/react-native-web-vite',
];
