import { defineTypedConfig } from '../types';

export const javascriptConfig = defineTypedConfig({
  plugins: ['eslint'],
  rules: {
    'eslint/accessor-pairs': ['error', { enforceForClassMembers: true, setWithoutGet: true }],
    'eslint/array-callback-return': 'error',
    'eslint/arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
    'eslint/block-scoped-var': 'error',
    'eslint/constructor-super': 'error',
    'eslint/default-case-last': 'error',
    'eslint/eqeqeq': ['error', 'smart'],
    'eslint/for-direction': 'error',
    'eslint/new-cap': ['error', { capIsNew: false, newIsCap: true, properties: true }],
    'eslint/no-alert': 'error',
    'eslint/no-array-constructor': 'error',
    'eslint/no-async-promise-executor': 'error',
    'eslint/no-caller': 'error',
    'eslint/no-case-declarations': 'error',
    'eslint/no-class-assign': 'error',
    'eslint/no-compare-neg-zero': 'error',
    'eslint/no-cond-assign': ['error', 'always'],
    'eslint/no-const-assign': 'error',
    'eslint/no-constant-binary-expression': 'error',
    'eslint/no-constant-condition': ['error', { checkLoops: 'allExceptWhileTrue' }],
    'eslint/no-constructor-return': 'error',
    'eslint/no-control-regex': 'error',
    'eslint/no-debugger': 'error',
    'eslint/no-delete-var': 'error',
    'eslint/no-div-regex': 'error',
    'eslint/no-dupe-class-members': 'error',
    'eslint/no-dupe-else-if': 'error',
    'eslint/no-dupe-keys': 'error',
    'eslint/no-duplicate-case': 'error',
    'eslint/no-duplicate-imports': ['error', { allowSeparateTypeImports: false, includeExports: false }],
    'eslint/no-else-return': ['error', { allowElseIf: false }],
    'eslint/no-empty': ['error', { allowEmptyCatch: true }],
    'eslint/no-empty-character-class': 'error',
    'eslint/no-empty-function': ['error', { allow: ['arrowFunctions'] }],
    'eslint/no-empty-pattern': 'error',
    'eslint/no-empty-static-block': 'error',
    'eslint/no-eval': 'error',
    'eslint/no-ex-assign': 'error',
    'eslint/no-extend-native': 'error',
    'eslint/no-extra-bind': 'error',
    'eslint/no-extra-boolean-cast': ['error', { enforceForInnerExpressions: true }],
    'eslint/no-extra-label': 'error',
    'eslint/no-fallthrough': 'error',
    'eslint/no-func-assign': 'error',
    'eslint/no-global-assign': 'error',
    'eslint/no-import-assign': 'error',
    'eslint/no-invalid-regexp': 'error',
    'eslint/no-irregular-whitespace': 'error',
    'eslint/no-iterator': 'error',
    'eslint/no-label-var': 'error',
    'eslint/no-labels': ['error', { allowLoop: false, allowSwitch: false }],
    'eslint/no-lone-blocks': 'error',
    'eslint/no-lonely-if': 'error',
    'eslint/no-loop-func': 'error',
    'eslint/no-loss-of-precision': 'error',
    'eslint/no-misleading-character-class': 'error',
    'eslint/no-multi-assign': 'error',
    'eslint/no-multi-str': 'error',
    'eslint/no-new': 'error',
    'eslint/no-new-func': 'error',
    'eslint/no-new-native-nonconstructor': 'error',
    'eslint/no-new-wrappers': 'error',
    'eslint/no-nonoctal-decimal-escape': 'error',
    'eslint/no-obj-calls': 'error',
    'eslint/no-object-constructor': 'error',
    'eslint/no-proto': 'error',
    'eslint/no-prototype-builtins': 'error',
    'eslint/no-redeclare': 'error',
    'eslint/no-regex-spaces': 'error',
    'eslint/no-restricted-globals': [
      'error',
      { message: 'Use `globalThis` instead.', name: 'global' },
      { message: 'Use `globalThis` instead.', name: 'self' },
    ],
    'eslint/no-self-assign': ['error', { props: true }],
    'eslint/no-self-compare': 'error',
    'eslint/no-sequences': 'error',
    'eslint/no-setter-return': 'error',
    'eslint/no-shadow-restricted-names': 'error',
    'eslint/no-sparse-arrays': 'error',
    'eslint/no-template-curly-in-string': 'error',
    'eslint/no-this-before-super': 'error',
    'eslint/no-throw-literal': 'off',
    'eslint/no-unassigned-vars': 'error',
    'eslint/no-undef': 'error',
    'eslint/no-unexpected-multiline': 'error',
    'eslint/no-unmodified-loop-condition': 'error',
    'eslint/no-unneeded-ternary': ['error', { defaultAssignment: false }],
    'eslint/no-unreachable': 'error',
    'eslint/no-unsafe-finally': 'error',
    'eslint/no-unsafe-negation': 'error',
    'eslint/no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
    'eslint/no-unused-expressions': [
      'error',
      { allowShortCircuit: true, allowTaggedTemplates: true, allowTernary: true },
    ],
    'eslint/no-unused-labels': 'error',
    'eslint/no-unused-private-class-members': 'error',
    'eslint/no-unused-vars': [
      'error',
      {
        args: 'none',
        caughtErrors: 'none',
        vars: 'all',
        argsIgnorePattern: '^_',
        ignoreRestSiblings: true,
        varsIgnorePattern: '^_',
      },
    ],
    'eslint/no-useless-backreference': 'error',
    'eslint/no-useless-call': 'error',
    'eslint/no-useless-catch': 'error',
    'eslint/no-useless-computed-key': 'error',
    'eslint/no-useless-concat': 'error',
    'eslint/no-useless-constructor': 'error',
    'eslint/no-useless-escape': 'error',
    'eslint/no-useless-rename': 'error',
    'eslint/no-useless-return': 'error',
    'eslint/no-var': 'error',
    'eslint/no-with': 'error',
    'eslint/operator-assignment': ['error', 'always'],
    'eslint/prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
    'eslint/prefer-destructuring': ['error', { enforceForRenamedProperties: true }],
    'eslint/prefer-exponentiation-operator': 'error',
    'eslint/prefer-numeric-literals': 'error',
    'eslint/prefer-object-has-own': 'error',
    'eslint/prefer-promise-reject-errors': 'error',
    'eslint/prefer-rest-params': 'error',
    'eslint/prefer-spread': 'error',
    'eslint/prefer-template': 'error',
    'eslint/preserve-caught-error': 'error',
    'eslint/radix': 'error',
    'eslint/require-yield': 'error',
    'eslint/sort-vars': 'error',
    'eslint/symbol-description': 'error',
    'eslint/unicode-bom': ['error', 'never'],
    'eslint/use-isnan': ['error', { enforceForIndexOf: true, enforceForSwitchCase: true }],
    'eslint/valid-typeof': ['error', { requireStringLiterals: true }],
    'eslint/vars-on-top': 'error',
    'eslint/yoda': ['error', 'never'],
  },
});
