import { commonJsFiles, dtsFiles, javaScriptFiles, testFiles } from '../globs';
import { defineTypedConfig } from '../types';

export const overridesConfig = defineTypedConfig({
  overrides: [
    {
      files: [...dtsFiles],
      rules: {
        'eslint/no-duplicate-imports': 'off',
        'eslint/no-undef': 'off',
        'eslint/no-unused-vars': 'off',
        'import/unambiguous': 'off',
        'unicorn/require-module-specifiers': 'off',
      },
    },
    {
      files: [...javaScriptFiles],
      rules: {
        'eslint/complexity': 'off',
        'jsdoc/check-tag-names': 'off',
        'jsdoc/no-defaults': 'off',
        'typescript/await-thenable': 'off',
        'typescript/consistent-type-exports': 'off',
        'typescript/dot-notation': 'off',
        'typescript/no-array-delete': 'off',
        'typescript/no-base-to-string': 'off',
        'typescript/no-confusing-void-expression': 'off',
        'typescript/no-deprecated': 'off',
        'typescript/no-duplicate-type-constituents': 'off',
        'typescript/no-floating-promises': 'off',
        'typescript/no-for-in-array': 'off',
        'typescript/no-implied-eval': 'off',
        'typescript/no-meaningless-void-operator': 'off',
        'typescript/no-misused-promises': 'off',
        'typescript/no-misused-spread': 'off',
        'typescript/no-mixed-enums': 'off',
        'typescript/no-redundant-type-constituents': 'off',
        'typescript/no-unnecessary-boolean-literal-compare': 'off',
        'typescript/no-unnecessary-condition': 'off',
        'typescript/no-unnecessary-qualifier': 'off',
        'typescript/no-unnecessary-template-expression': 'off',
        'typescript/no-unnecessary-type-arguments': 'off',
        'typescript/no-unnecessary-type-assertion': 'off',
        'typescript/no-unnecessary-type-conversion': 'off',
        'typescript/no-unnecessary-type-parameters': 'off',
        'typescript/no-unsafe-argument': 'off',
        'typescript/no-unsafe-assignment': 'off',
        'typescript/no-unsafe-call': 'off',
        'typescript/no-unsafe-enum-comparison': 'off',
        'typescript/no-unsafe-member-access': 'off',
        'typescript/no-unsafe-return': 'off',
        'typescript/no-unsafe-unary-minus': 'off',
        'typescript/no-useless-default-assignment': 'off',
        'typescript/non-nullable-type-assertion-style': 'off',
        'typescript/only-throw-error': 'off',
        'typescript/prefer-find': 'off',
        'typescript/prefer-includes': 'off',
        'typescript/prefer-nullish-coalescing': 'off',
        'typescript/prefer-optional-chain': 'off',
        'typescript/prefer-promise-reject-errors': 'off',
        'typescript/prefer-readonly': 'off',
        'typescript/prefer-reduce-type-parameter': 'off',
        'typescript/prefer-regexp-exec': 'off',
        'typescript/prefer-return-this-type': 'off',
        'typescript/prefer-string-starts-ends-with': 'off',
        'typescript/related-getter-setter-pairs': 'off',
        'typescript/require-array-sort-compare': 'off',
        'typescript/require-await': 'off',
        'typescript/restrict-plus-operands': 'off',
        'typescript/restrict-template-expressions': 'off',
        'typescript/return-await': 'off',
        'typescript/use-unknown-in-catch-callback-variable': 'off',
        'unicorn/no-null': 'off',
        'unicorn/require-module-specifiers': 'off',
      },
    },
    {
      files: [...testFiles],
      globals: {
        afterAll: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        bench: 'readonly',
        describe: 'readonly',
        expect: 'readonly',
        expectTypeOf: 'readonly',
        it: 'readonly',
        suite: 'readonly',
        test: 'readonly',
        vi: 'readonly',
      },
      rules: {
        'eslint/no-unused-expressions': 'off',
      },
    },
    {
      files: [...commonJsFiles],
      rules: {
        'typescript/no-import-type-side-effects': 'off',
      },
    },
  ],
});
