import { defineConfig } from 'oxlint';

export const reactConfig = defineConfig({
  options: {
    typeAware: true,
  },
  plugins: ['react', 'react-perf'],
  jsPlugins: [
    {
      name: 'stylistic',
      specifier: import.meta.resolve('@stylistic/eslint-plugin'),
    },
  ],
  rules: {
    'react/button-has-type': 'error',
    'react/exhaustive-deps': 'error',
    'react/function-component-definition': ['error', { namedComponents: 'function-declaration' }],
    'react/iframe-missing-sandbox': 'error',
    'react/jsx-key': 'error',
    'react/jsx-no-comment-textnodes': 'warn',
    'react/jsx-no-constructed-context-values': 'error',
    'react/jsx-no-script-url': 'warn',
    'react/jsx-no-target-blank': 'error',
    'react/jsx-no-useless-fragment': 'off',
    'react/no-array-index-key': 'warn',
    'react/no-children-prop': 'error',
    'react/no-clone-element': 'warn',
    'react/no-danger': 'warn',
    'react/no-danger-with-children': 'error',
    'react/no-did-mount-set-state': 'warn',
    'react/no-direct-mutation-state': 'error',
    'react/no-find-dom-node': 'error',
    'react/no-namespace': 'error',
    'react/no-redundant-should-component-update': 'error',
    'react/no-render-return-value': 'error',
    'react/no-unsafe': 'warn',
    'react/no-will-update-set-state': 'warn',
    'react/rules-of-hooks': 'error',
    'react/self-closing-comp': 'error',
    'react/void-dom-elements-no-children': 'error',
    'react-perf/jsx-no-jsx-as-prop': 'error',
    'stylistic/jsx-curly-newline': 'off',
    'stylistic/jsx-newline': ['error', { prevent: false }],

    'react/checked-requires-onchange-or-readonly': undefined,
    'react/display-name': 'off',
    'react/forbid-component-props': undefined,
    'react/forbid-dom-props': undefined,
    'react/forbid-elements': undefined,
    'react/forward-ref-uses-ref': 'off',
    'react/hook-use-state': 'error',
    'react/jsx-boolean-value': 'off',
    'react/jsx-curly-brace-presence': undefined,
    'react/jsx-filename-extension': 'off',
    'react/jsx-fragments': 'off',
    'react/jsx-handler-names': undefined,
    'react/jsx-max-depth': undefined,
    'react/jsx-no-duplicate-props': undefined,
    'react/jsx-no-literals': undefined,
    'react/jsx-no-undef': undefined,
    'react/jsx-pascal-case': 'off',
    'react/jsx-props-no-spread-multi': undefined,
    'react/jsx-props-no-spreading': undefined,
    'react/no-did-update-set-state': 'off',
    'react/no-is-mounted': undefined,
    'react/no-multi-comp': undefined,
    'react/no-object-type-as-default-prop': 'off',
    'react/no-react-children': undefined,
    'react/no-set-state': undefined,
    'react/no-string-refs': 'off',
    'react/no-this-in-sfc': undefined,
    'react/no-unescaped-entities': undefined,
    'react/no-unknown-property': 'off',
    'react/no-unstable-nested-components': 'off',
    'react/only-export-components': undefined,
    'react/prefer-es6-class': undefined,
    'react/prefer-function-component': undefined,
    'react/react-in-jsx-scope': undefined,
    'react/require-render-return': undefined,
    'react/state-in-constructor': undefined,
    'react/style-prop-object': undefined,
    'react/syntax': 'error',
    'react/todo': 'error',
    'react/unsupported-syntax': 'error',
    'react/use-memo': 'error',
    'react/void-use-memo': 'error',

    'react/capitalized-calls': 'error',
    'react/error-boundaries': 'error',
    'react/exhaustive-effect-dependencies': 'error',
    'react/globals': 'error',
    'react/hooks': 'error',
    'react/immutability': 'error',
    'react/incompatible-library': 'error',
    'react/invariant': 'error',
    'react/memo-dependencies': 'error',
    'react/no-deriving-state-in-effects': 'error',
    'react/preserve-manual-memoization': 'error',
    'react/purity': 'error',
    'react/refs': 'error',
    'react/rule-suppression': 'error',
    'react/set-state-in-effect': 'error',
    'react/set-state-in-render': 'error',
    'react/static-components': 'error',

    'react-perf/jsx-no-new-array-as-prop': undefined,
    'react-perf/jsx-no-new-function-as-prop': undefined,
    'react-perf/jsx-no-new-object-as-prop': undefined,
  },
});
