import { defineTypedConfig } from '../types';

export const typescriptRulesConfig = defineTypedConfig({
  plugins: ['typescript'],
  options: {
    typeAware: true,
  },
  rules: {
    'typescript/adjacent-overload-signatures': 'error',
    'typescript/array-type': ['error', { default: 'generic', readonly: 'generic' }],
    'typescript/await-thenable': 'error',
    'typescript/ban-ts-comment': ['error', { 'ts-ignore': 'allow-with-description' }],
    'typescript/ban-tslint-comment': 'error',
    'typescript/class-literal-property-style': 'error',
    'typescript/consistent-generic-constructors': ['error', { option: 'constructor' }],
    'typescript/consistent-indexed-object-style': ['error', 'record'],
    'typescript/consistent-type-assertions': ['error', { assertionStyle: 'angle-bracket' }],
    'typescript/consistent-type-definitions': 'error',
    'typescript/consistent-type-exports': 'error',
    'typescript/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
    'typescript/dot-notation': ['error', { allowKeywords: true }],
    'typescript/no-array-delete': 'error',
    'typescript/no-base-to-string': 'error',
    'typescript/no-deprecated': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-empty-object-type': ['error', { allowInterfaces: 'with-single-extends', allowObjectTypes: 'never' }],
    'typescript/no-explicit-any': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-meaningless-void-operator': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-misused-spread': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-non-null-assertion': 'error',
    'typescript/no-redundant-type-constituents': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-condition': ['error', { allowConstantLoopConditions: 'only-allowed-literals' }],
    'typescript/no-unnecessary-parameter-property-assignment': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-unary-minus': 'error',
    'typescript/no-useless-empty-export': 'error',
    'typescript/no-var-requires': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/require-array-sort-compare': 'error',
    'typescript/restrict-template-expressions': ['error', { allowNumber: true }],
    'typescript/triple-slash-reference': 'error',
    'typescript/unbound-method': 'error',
  },
});
