import type { Format, TransformedToken } from 'style-dictionary/types';

/**
 * Generates CSS custom properties for design tokens.
 * Outputs responsive tokens with @media query overrides.
 */
export const cssVariablesFormat: Format = {
  name: 'tailwind/css-variables',
  format({ dictionary, options }) {
    const mobileTokens = options.mobileTokens as Map<string, unknown> | undefined;
    const desktopTokens = options.desktopTokens as Map<string, unknown> | undefined;
    const breakpoint = (options.breakpoint as string | undefined) ?? '768px';

    const baseVars: Array<string> = [];
    const responsiveVars: Array<string> = [];

    for (const token of dictionary.allTokens) {
      const cssName = tokenToCssName(token);
      const value = formatCssValue(token);

      // Check if this token has responsive variants
      if (mobileTokens && desktopTokens) {
        const tokenPath = token.path.join('.');
        const mobileValue = mobileTokens.get(tokenPath);
        const desktopValue = desktopTokens.get(tokenPath);

        if (mobileValue !== undefined && desktopValue !== undefined && mobileValue !== desktopValue) {
          baseVars.push(`  ${cssName}: ${formatValue(mobileValue)};`);
          responsiveVars.push(`  ${cssName}: ${formatValue(desktopValue)};`);
          continue;
        }
      }

      baseVars.push(`  ${cssName}: ${value};`);
    }

    let output = `/* Generated by @2digits/design-tokens - do not edit manually */\n\n`;

    output += `:root {\n${baseVars.join('\n')}\n}\n`;

    if (responsiveVars.length > 0) {
      const indentedVars = responsiveVars.map((v) => `  ${v}`).join('\n');

      output += `\n@media (min-width: ${breakpoint}) {\n`;
      output += `  :root {\n${indentedVars}\n  }\n`;
      output += `}\n`;
    }

    return output;
  },
};

function tokenToCssName(token: TransformedToken): string {
  return `--${token.path
    .map((p) =>
      p
        .replaceAll(/([a-z])([A-Z])/g, '$1-$2')
        .replaceAll(/[\s_]+/g, '-')
        .toLowerCase(),
    )
    .join('-')}`;
}

function formatCssValue(token: TransformedToken): string {
  if (typeof token.$value === 'string') {
    return token.$value;
  }
  if (typeof token.$value === 'number') {
    if (token.$type === 'color') {
      return String(token.$value);
    }

    // For spacing/sizing, assume px if raw number
    return `${token.$value}px`;
  }

  return String(token.$value);
}

function formatValue(value: unknown): string {
  if (typeof value === 'string') {
    return value;
  }
  if (typeof value === 'number') {
    return `${value}px`;
  }

  return String(value);
}
