name: 🛂 CI/CD

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    branches:
      - '**'

jobs:
  build:
    name: ⚗️ Lint, typecheck and format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: 1
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version-file: package.json
          cache: true

      - name: 🧱 Build
        run: vp run build

      - name: 🏷️ Type-check
        run: vp run types

      - name: ⚗️ Check
        run: vp check

      - name: 🧪 Test
        run: vp run test

      - name: 🔍 Lint
        run: vp run lint

      - name: 🪄 Format
        run: vp run format

      - name: ✂️ Knip
        run: vp run knip
