name: 🛂 CI/CD

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    branches:
      - '**'

jobs:
  build:
    name: ⚗️ Lint, typecheck and format
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: 1
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@8ecb39174989ce55af90f45cf55b02738599831d # v1
        with:
          node-version-file: package.json
          cache: true

      - name: 🐰 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: 🧱 Build
        run: vp run build

      - name: 🏷️ Type-check
        run: vp run types

      - name: ⚗️ Check
        run: vp check

      - name: 🧪 Test
        run: vp test run

      - name: 🔍 Lint
        run: vp run lint

      - name: 🪄 Format
        run: vp run format

      - name: ✂️ Knip
        run: vp run knip
