name: 🚀 pkg.pr.new Workflow

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  publish:
    name: 📦 Publish Preview Packages
    runs-on: ubuntu-latest
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@e34774bccb4e7d7f2e23514ca980177a71425e43 # v1
        with:
          node-version-file: package.json
          cache: true

      - name: 🛸 Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5

      - name: 🐰 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: Build
        run: vp run build

      - name: 🚀 Publish with pkg.pr.new
        run: vp exec pkg-pr-new publish './packages/*' --packageManager pnpm --pnpm
