name: 🚀 pkg.pr.new Workflow

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  publish:
    name: 📦 Publish Preview Packages
    runs-on: ubuntu-latest
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version-file: package.json
          cache: true

      - name: 🛸 Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Build
        run: vp run build

      - name: 🚀 Publish with pkg.pr.new
        run: vp exec pkg-pr-new publish './packages/*' --packageManager pnpm --pnpm
