name: 🚀 pkg.pr.new Workflow

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  publish:
    name: 📦 Publish Preview Packages
    runs-on: ubuntu-latest
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1.10.0
        with:
          node-version-file: package.json
          cache: true

      - name: 🛸 Setup PNPM
        uses: pnpm/action-setup@739bfe42ca9233c5e6aca07c1a25a9d34aca49b0 # v6.0.7

      - name: Build
        run: vp run build

      - name: 🚀 Publish with pkg.pr.new
        run: vp exec pkg-pr-new publish './packages/*' --packageManager pnpm --pnpm
