name: 💠 Publish

concurrency: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  publish:
    name: 🦋 Changesets
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_COLOR: 1
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: package.json
          cache: true
          registry-url: 'https://registry.npmjs.org'

      - name: 🐰 Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2

      - name: 🧪 Test, lint, format, build, build and type-check
        run: vp exec turbo run build test lint:root lint:oxlint format types

      - name: 🏗️ Build packages
        run: vp exec turbo run build --force

      - name: 🪄 Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: vp run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
