name: ✉️ Tegami PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  preview:
    name: 📝 Release preview
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version-file: package.json
          cache: true

      - name: 📝 Generate release preview
        run: vp run tegami pr preview --artifact tegami-pr-preview.md

      - name: 📤 Upload release preview
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: tegami-pr-preview
          path: tegami-pr-preview.md
