name: ✉️ Tegami PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  preview:
    name: 📝 Release preview
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@1b32467adbe183473499fd9d5d372c3ed9641754 # v1.18.0
        with:
          node-version-file: package.json
          cache: true

      - name: 📝 Generate release preview
        run: vp run tegami pr preview --artifact tegami-pr-preview.md

      - name: 📤 Upload release preview
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tegami-pr-preview
          path: tegami-pr-preview.md
