name: ✉️ Tegami PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  preview:
    name: 📝 Release preview
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: 🗃️ Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: ⚡Setup Vite+
        uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
        with:
          node-version-file: package.json
          cache: true

      - name: 📝 Generate release preview
        run: vp run tegami pr preview --artifact tegami-pr-preview.md

      - name: 📤 Upload release preview
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tegami-pr-preview
          path: tegami-pr-preview.md
